export const AI_MODELS: string[] = [
  // ---- Large Language Models ----
  "GPT-4o",
  "GPT-4",
  "GPT-3.5",
  "Claude 3 Opus",
  "Claude 3 Sonnet",
  "Claude 3 Haiku",
  "Gemini 1.5 Pro",
  "Gemini 1.0 Pro",
  "Llama 3 70B",
  "Llama 3 8B",
  "Mixtral 8x22B",
  "Mixtral 8x7B",
  "Mistral Large",
  "Mistral 7B",
  "Command R+",
  "Command R",
  "Grok-1",
  "Titan Text",
  "Qwen-2 72B",
  "Luminous Supreme",
  "Ernie Bot 4.0",
  "Arctic (Snowflake)",

  // ---- Image & Multimodal Models ----
  "DALL·E 3",
  "Midjourney v6",
  "Stable Diffusion XL (SDXL)",
  "Stable Diffusion 2.1",
  "Imagen 2",
  "Firefly 3",
  "Playground v2",
  "Gemini Image 2",
  "Ideogram 1.0",
  "Stable Cascade",
  "Kandinsky 3.0",
  "Reimagine XL",

  // ---- Audio / Video Generation ----
  "Suno v3",
  "Stable Audio 2.0",
  "Sora (video)",
  "Veo (video)",
  "Pika 1.0",
  "Runway Gen-2",
] 