export const TAGS: string[] = [
  "Marketing",
  "Twitter",
  "Minimalism",
  "Startups",
  "Investissement",
  "IA",
  "Copywriting",
  "Skincare",
  "Vente",
  "Méditation",
  "Débutants",
  "Bien-être",
  "Data",
  "Optimisation",
] 